title = "MaterialBet Bitcoin Gambling News BTC Sports & Casino Blog"
baseURL = ""
theme = "ananke-mod"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
  	contentDir = "content/en-gb"
    title = "MaterialBet"
    languageName = "English"
    weight = 1
  [[languages.en.menu.main]]
    url    = "/en/blog"
    name   = "Blog"
    weight = 1
  [[languages.en.menu.main]]
    url    = "/en/promotions"
    name   = "Promotions"
    weight = 0

  [languages.fr]
  	contentDir = "content/fr-fr"
    title = "Mon blogue"
    languageName = "Française"
    weight = 2
  [[languages.fr.menu.main]]
    url    = "/fr/blog"
    name   = "Blog"
    weight = 1
  [[languages.fr.menu.main]]
    url    = "/fr/promotions"
    name   = "Promotions"
    weight = 0

  [languages.zh]
  	contentDir = "content/zh-hans-cn"
    title = "MaterialBet"
    languageName = "简体中文"
    weight = 3
  [[languages.zh.menu.main]]
    url    = "/zh/blog"
    name   = "博客"
    weight = 1
  [[languages.zh.menu.main]]
    url    = "/zh/promotions"
    name   = "活动促销"
    weight = 0

  [languages.ko]
  	contentDir = "content/ko-kr"
    title = "MaterialBet"
    languageName = "조선말"
    weight = 4
  [[languages.ko.menu.main]]
    url    = "/ko/blog"
    name   = "블로그"
    weight = 1
  [[languages.ko.menu.main]]
    url    = "/ko/promotions"
    name   = "프로모션"
    weight = 0

  [languages.id]
  	contentDir = "content/id-id"
    title = "MaterialBet"
    languageName = "Bahasa Indonesia"
    weight = 5
  [[languages.id.menu.main]]
    url    = "/id/blog"
    name   = "Blog"
    weight = 1
  [[languages.id.menu.main]]
    url    = "/id/promotions"
    name   = "Promosi"
    weight = 0

  [languages.ru]
  	contentDir = "content/ru-ru"
    title = "MaterialBet"
    languageName = "Русский"
    weight = 6
  [[languages.ru.menu.main]]
    url    = "/ru/blog"
    name   = "блог"
    weight = 1
  [[languages.ru.menu.main]]
    url    = "/ru/promotions"
    name   = "промо акции"
    weight = 0

  [languages.tr]
  	contentDir = "content/tr-tr"
    title = "MaterialBet"
    languageName = "Türkçe"
    weight = 7
  [[languages.tr.menu.main]]
    url    = "/tr/blog"
    name   = "Blog"
    weight = 1
  [[languages.tr.menu.main]]
    url    = "/tr/promotions"
    name   = "Promosyonlar"
    weight = 0

[params]
  background_color_class = "bg-near-black"
  featured_image = "/https://res.cloudinary.com/betengine/image/fetch/c_fit,f_auto,q_auto/https://cdn.cloudbet.com/Cricket-World-Cup-Hero.jpg"
  recent_posts_number = 7
